# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Alex Oliveira
author:      Alex Oliveira
email:       ''
description: 'Software, Systems and Thinking.'
#baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://alexoliveira.cc' # The base hostname & protocol for your site
twitter:     'https://twitter.com/kurko'
github:      'https://github.com/kurko'
instagram:   'https://instagram.com/alrowan'
facebook:    ''
linkedin:    'https://www.linkedin.com/in/alexandredeoliveira/'

markdown:  kramdown
permalink: none
paginate:  15

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-mentions
  - jekyll-feed
  - jekyll-redirect-from

include:
  - _pages
  - _essay

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
permalink: /:categories/:title

feed:
  path: atom.xml

#collections_dir: obsidian

collections:
  essay:
    output: true
    permalink: /:title

  guide:
    output: true
    permalink: /:title

# Pages path
defaults:
  - scope:
      path: ''
    values:
      layout: post

  - scope:
      path: 'obsidian/essay'
    values:
      permalink: essay/:title

  - scope:
      path: 'obsidian/guide'
    values:
      permalink: guide/:title

  - scope:
      path: 'obsidian*'
    values:
      permalink: /:basename

  - scope:
      path: 'essay'
    values:
      layout: post

  - scope:
      path: 'guide'
    values:
      layout: post

  - scope:
      path: '_pages'
    values:
      layout: page
      permalink: /:basename
